# Antecedentes {#sec-antecedentes}

\todo{Cambiar antecedentes para enfocarla más en establecer el contexto y la relevancia general del problema}

Los trastornos depresivos y de ansiedad afectan profundamente las capacidades cognitivas de los individuos, más allá de los síntomas emocionales [@cerecero-garcia2020]. Estos problemas incluyen dificultades en la atención, la memoria y la flexibilidad cognitiva [@anacker2017], siendo algunos de los aspectos más debilitantes de estos padecimientos [@sandi2013]. Comprender mejor los mecanismos subyacentes a estas alteraciones es crucial para desarrollar tratamientos más efectivos. En este contexto, la fluoxetina, un \ac{isrs}, ha cobrado relevancia [@marwari2018]. El estudio de sus efectos sobre procesos desregulados en la depresión, como la flexibilidad cognitiva, puede abrir nuevas vías terapéuticas.

En modelos animales, el estrés crónico afecta negativamente al \ac{gd} [@conrad2008; @hei2019; @lucassen2016], induce comportamientos de tipo ansiosos y depresivos [@hill2012; @mineur2006] y dificulta la flexibilidad cognitiva [@jett2017]. Por otro lado, la fluoxetina ha mostrado potencial para mejorar estos síntomas [@dulawa2004], así como la flexibilidad cognitiva [@marwari2018]. Por otro lado, estudios *post mortem* muestran una reducción en el volumen del hipocampo (\ac{gd}, \ac{ca}1 y \ac{ca}3) en individuos con depresión [@sheline1996; @steffens2000; @cobb2013; @huang2013; @treadway2015], mientras que el tratamiento con \ac{isrs} ha demostrado aumentar el volumen hipocampal [@boldrini2009; @boldrini2012; @boldrini2013] y prevenir la atrofia de dendritas relacionada con el estrés crónico [@bessa2009]. 

El \ac{mwm} es una herramienta eficaz para evaluar la memoria espacial [@othman2022] y la flexibilidad cognitiva [@garthe2009] en roedores, permitiendo estudiar la relación entre estas capacidades y la función hipocampal [@garthe2013]. Este estudio utilizará el \ac{mwm} para investigar el impacto de la fluoxetina en la flexibilidad cognitiva de ratones sometidos a \ac{cums}, buscando establecer una base para posibles enfoques terapéuticos en humanos.