# Discusión {#sec-discusion}

## Efectos de la fluoxetina en los entrenamientos reversa

***Efecto principal del tratamiento con fluoxetina***

Nuestro ANOVA mixto ([@tbl-latenciaRevTabla]) sobre las latencias en la fase de reversa reveló un efecto principal significativo del tratamiento (`F(1,25)=12.139, p=.002,` $\eta^2$`=0.111`), de manera que, independientemente de la condición de estrés, los ratones tratados con fluoxetina mostraron menores latencias de escape en comparación con los tratados con solución salina ([@fig-latenciaspost]). Este hallazgo sugiere que la fluoxetina facilita el reaprendizaje en el \ac{mwm}, en concordancia con estudios previos que describen cómo este fármaco mejora la flexibilidad cognitiva y promueve la \ac{nha} [@marwari2018; @malberg2000], procesos que permiten actualizar memorias [@amelchenko2023; @amelchenko2023a] y adaptarse a cambios ambientales [@li2008].

Sin embargo, este resultado por sí solo no basta para afirmar que la fluoxetina mejora directamente la memoria espacial [@maei2009; @young2021]. Se ha demostrado que roedores con lesiones hipocampales [@morris1982; @gallagher1993] también pueden reducir la latencia de escape en el \ac{mwm} debido a factores como alteraciones en la velocidad de nado, la motivación o la aversión al agua [@garthe2013]. No obstante, una disminución consistente en las latencias generalmente refleja algún grado de aprendizaje sobre la ubicación de la plataforma [@andersen2021].

Actualmente se reconoce que los \ac{isrs} no solo ejercen efectos antidepresivos modulando el sistema serotoninérgico [@harmer2017], sino que también promueven procesos de plasticidad sináptica en regiones como la \ac{mpfc} y el \ac{gd} [@bjorkholm2016] que restauran la conectividad entre estas áreas. Aunque otras áreas [@mayavetencourt2008], como la amígdala [@mcewen2016], también son susceptibles a los cambios neuroplásticos inducidos por los \ac{isrs}, sus efectos sobre el \ac{gd} siguen siendo un área de investigación activa por su papel fundamental en las memorias episódicas y la regulación emocional [@kitahara2016] que podría subyacer las mejoras observadas en el reaprendizaje y la adaptación a nuevas contingencias reportadas con la fluoxetina [@marwari2018].

***Interacción tratamiento × estrés: el estrés disminuye el efecto de la fluoxetina***

Además, la interacción tratamiento × estrés fue significativa (`F(1,25)=6.988, p=.014,` $\eta^2$`=0.067`) ([@tbl-latenciaRevTabla]), lo que indica que el estrés crónico modula la eficacia de la fluoxetina en el reaprendizaje espacial ([@fig-latenciaspost]). En el grupo expuesto al protocolo \ac{cums}, los ratones tratados con fluoxetina no alcanzaron reducciones de latencia comparables a las de sus contrapartes no estresadas, lo que sugiere que la exposición prolongada a estresores interfiere con los mecanismos moleculares y celulares mediados por los \ac{isrs} [@belleau2019].

Este resultado concuerda con numerosos estudios que han documentado cómo el aumento sostenido de glucocorticoides durante el estrés crónico reduce la proliferación y supervivencia de progenitores neuronales, además de disminuir la expresión de BDNF en el hipocampo [@fuchs1998; @odaka2017; @krontira2024]. Esta disrupción de la neurogénesis y de la plasticidad hipocampal podría limitar la capacidad de los \ac{isrs} para ejercer sus efectos positivos ante el estrés crónico [@dealcubierre2023; @kino2015], por lo que se deben realizar investigaciones adicionales para comprender cómo el estrés crónico afecta la respuesta a los \ac{isrs} y la plasticidad neuronal en el hipocampo [@mcewen2016].

En conjunto, estos resultados subrayan la importancia de considerar el estado de estrés crónico al evaluar la eficacia de la fluoxetina en trastornos cognitivos [@chiarotti2017]. Se ha demostrado que la presencia de estresores persistentes atenúa el beneficio terapéutico de la fluoxetina [@alboni2017] en dominios como la \ac{nha} y niveles de \ac{bdnf}, ambos implicados en la memoria espacial y la flexibilidad cognitiva [@harmer2017], lo que resalta la necesidad de enfoques terapéuticos que también apunten a reducir la carga de estrés para optimizar los resultados clínicos [@branchi2011].

## Efectos del Estrés Crónico sobre el aprendizaje espacial

***La fluoxetina reduce preferencia por zona blanco en el grupo de estrés crónico en la Prueba-2 de Retención***

En la prueba 2 (*Retención de la memoria*), los ratones del grupo de \textcolor{blue}{Fluoxetina} + \textcolor{red}{CUMS} fueron los únicos que no presentan una *preferencia* (media mayor al 11% definido en @sec-metodologia como preferencia) por la *zona* blanco (@fig-zonaP2Plot), es decir, retuvieron menos la memoria espacial previamente adquirida (@fig-cuadranteP1Plot).

De acuerdo al *modelo estándar de consolidación* [@alvarez1994; @knowlton1998], \todo{Aquí no le entendí al Dr. Pascal si sugería que cambiara la redacción o la idea:} tradicionalmente se creía que el hipocampo jugaba un papel limitado de almacenamiento temporal para las memorias recientes. Teorías más recientes consideran que el hipocampo retiene un papel crucial en el procesamiento de memorias remotas, particularmente aquellas ricas en detalles contextuales o [episódicos](AppendixB.qmd#term-id-2) (ver @sec-consolidacion) [@kandel2014]. De acuerdo a evidencia clínica y experimental, el modelo de traza múltiple [@nadel1997; @nadel2000; @nadel2007] confirma que el hipocampo es necesario para la evocación de memorias al proporcionar un contexto espacial y temporal del recuerdo [@kandel2014]. Recientemente, utilizando [BrdU](AppendixB.qmd#term-id-95) y [c-Fos](AppendixB.qmd#term-id-94) para identificar conjuntos neuronales reclutados en varias etapas de la memoria de [condicionamiento contextual al miedo](AppendixB.qmd#term-id-57), @kveim2024 demostraron que el [engrama](AppendixB.qmd#term-id-1) original del hipocampo se mantiene y es importante para la evocación de la memoria a largo plazo (`28 días`). A pesar de que los engramas del hipocampo permanecen después de la consolidación, en modelos de miedo contextual al miedo se reporta que la activación de estos engramas hipocampales es cada vez menor en comparación con la activación de engramas en otras zonas, como [amígdala](AppendixB.qmd#term-id-13) [@kitamura2017] y la [corteza prefrontal](AppendixB.qmd#term-id-68) [@goto2021]. 

Por otro lado, las memorias asociadas a engramas de neuronas más jóvenes son más propensas a ser modificadas que las memorias almacenadas por neuronas más viejas [@kveim2024], permitiendo la actualización o modificación de un recuerdo reciente [@tronson2007; @lee2009]. Debido a que muchas investigaciones [@akers2014; @epp2016; @scott2021; @lopez-oropeza2022; @weisz2012] reportan que un aumento en neurogénesis induce interferencia en memorias dependientes del hipocampo, observadas como un olvido, es plausible que la neurogénesis hipocampal esté jugando un papel en este fenómeno que observamos en la prueba de memoria remota en el grupo de \textcolor{blue}{Fluoxetina} + \textcolor{red}{CUMS}. \todo{discutir más por qué en este grupo y no en los otros. Lo discutí más abajo en perspectivas y limitaciones, o lo pongo mejor aquí?} En contraste, los animales tratados con salina retienen la memoria espacial previamente adquirida. Esto está en línea con estudios previos que han demostrado que el estrés crónico afecta negativamente la función cognitiva dependiente del hipocampo [@mcewen2016]. Estos efectos incluyen: disminución de la neurogénesis adulta [@hill2012], atrofia dendrítica [@bessa2009], disminución de la expresión de factores neurotróficos [@lucassen2016]. Estos cambios estructurales y funcionales en el hipocampo se asocian con déficits en la memoria espacial [@hill2012; @mineur2006] y la flexibilidad cognitiva [@jett2017]. 

Este olvido relacionado con la \ac{nha} está asociada con la hipótesis de "*limpieza de memorias*" [@anacker2017], un fenómeno donde las nuevas neuronas impiden la evocación de memorias antiguas [@epp2016]. Utilizando microscopía electrónica e imagenología, @toni2007 demostraron que las nuevas neuronas en el \ac{gd} se integran en circuitos existentes y forman sinapsis funcionales que compiten con neuronas existentes, un fenómeno que probablemente resulte en olvido [@guskjolen2023]. En línea con estas ideas, utilizando deleción genética, optogenética y quimiogenética, @guskjolen2023 encontraron que la *hipo-integración* de nuevas neuronas previene el olvido post entrenamiento de una memora contextual al miedo, mientras que la *hiper-integración* inducía olvido. 

El olvido mediado por la \ac{nha} parece ser un mecanismo adaptativo que permite la actualización y flexibilidad de la memoria, aunque la evidencia experimental que soporta esta hipótesis no emplea modelos causales [@lazic2014] que distingan entre correlación y causalidad [@lazic2010]. Si una memoria, como un pensamiento intrusivo, puede ser alterada durante un período lábil, existe la posibilidad de que la memoria pueda ser reconsolidada (modificada), resignificada o incluso eliminada. Si la NHA es un mecanismo que permite la reconsolidación u olvido de memorias y la formación de nuevas conexiones, podría constituir un blanco terapéutico, particularmente eficaz en el tratamiento de recuerdos fuertes e intrusivos, fobias e incluso adicciones [@tronson2007]. Sin embargo, la plasticidad es un arma de doble filo [@branchi2011] que también permite el fortalecimiento (@sec-sph) de una memoria intrusiva en este proceso de recuperación [@terada2021], potencialmente empeorando los síntomas aversivos cuando esta plasticidad se acopla con estímulos que generen [distrés](AppendixB.qmd#term-id-18) [@chiarotti2017; @carhart-harris2018; @alboni2017]. 

***Impacto del estrés y Fluoxetina sobre la Flexibilidad Cognitiva*** 

Uno de los hallazgos más importantes de este estudio es la demostración de que el estrés induce deficiencias significativas en la [flexibilidad cognitiva](AppendixB.qmd#term-id-19) de los ratones. Los ratones sometidos a estrés sin tratamiento de fluoxetina mostraron una disminución en su capacidad para adaptarse a nuevas configuraciones del laberinto, tal como se observa en las mayores *latencia de escape* en el primer día del entrenamiento reversa (@fig-latenciaspost), una *distancia promedio* mayor al annulus reversa (@fig-distanciaMedia) y un menor tiempo en la zona del annulus reversa (@fig-zonainteraccion). Estos efectos son consistentes con estudios previos que han demostrado que el estrés crónico afecta negativamente la función cognitiva dependiente del hipocampo [@mcewen2016]. 

El reaprendizaje de la plataforma oculta en la prueba reversa es un proceso que implica la formación de una nueva asociación de la memoria espacial y la supresión de la memoria previamente [adquirida](AppendixB.qmd#term-id-9) [@saab2011a], lo cuál permite guiar la conducta hacia la nueva meta ([flexibilidad cognitiva](AppendixB.qmd#term-id-19)). Aquí observamos que independientemente del factor estrés inducido por \textcolor{red}{estrés CUMS}, el primer día de los entrenamientos reversa, los animales tratados con \textcolor{blue}{fluoxetina} tardaban menos tiempo en localizar la plataforma en la nueva localización (@fig-latenciaspost). Adicionalmente, en el grupo de \textcolor{red}{estrés CUMS}, se observa que los animales tratados con de \textcolor{orange}{salina} presentaron estrategias "**perseverantes**" hasta el segundo día de los entrenamientos reversa (@fig-estrategiasPost). En contraste, los ratones tratados con \textcolor{blue}{fluoxetina} no presenta estrategias de perseverancia para el segundo día. Esto es relevante ya que el uso de estrategias perseverantes está relacionado con la integridad del hipocampo [@yu2019; @garthe2016] y su capacidad de actualizar información de manera más eficiente [@garthe2009]. Las estrategias perseverantes siguen representando una correcta ubicación espacial de la memoria antigua [@kempermann2022] pero reflejan una falta de flexibilidad cognitiva al no reconocer una modificación o actualización de las demandas del entorno. Esta perseverancia también se puede visualizar en los mapas de densidad de la prueba reversa (@fig-mapasprevs), donde los grupos tratados con \textcolor{orange}{salina} muestran una alta ocupación en la localización de la plataforma original, mientras que en los grupos de fluoxetina se concentra su movimiento en la nueva plataforma. Este fenómeno podría ser estudiado más a fondo con un protocolo donde se utilicen 2 o 3 entrenamientos reversa, similar al estudio de @amelchenko2023 y @amelchenko2023a. En ambos estudios, los tratamientos que alteraban la dinámica hipocampal (radiación y envejecimiento, respectivamente) dificultaban el uso y actualización de los mapas espaciales. Sin embargo, es hasta la segunda y tercera prueba reversa que se hizo evidente la diferencia entre los ratones con daño hipocampal y los controles.

Sumado a los entrenamientos, los resultados en la prueba reversa (@fig-cuadrantesPRevPlot, @fig-zonaPRevPlot) también sugieren que el estrés afecta la flexibilidad cognitiva de los ratones, lo que se manifiesta en una menor capacidad para adaptarse a la nueva configuración del laberinto. En línea con otras investigaciones [@epp2016; @garthe2009; @garthe2016; @li2023; @amelchenko2023; @amelchenko2023a], estos resultados sugieren que la flexibilidad de memorias espaciales se relaciona con la integridad del hipocampo, mientras que el estrés crónico dificulta el reaprendizaje. El hecho que la fluoxetina incrementa la NHA en modelos animales [@malberg2000] y humanos [@boldrini2009; @boldrini2012; @boldrini2013], además de promover la flexibilidad cognitiva [@marwari2018] y mitigar los efectos cognitivos del estrés [@li2022], sugiere que esta flexibilidad de la memoria espacial que observamos podría está mediado por la NHA. 


\todo{Como menciona el Dr. Pascar, mucha de esta información ya la había puesto. La resumí y le traté de dar un giro y otra perspectiva a esta información.} 

\todo{Nueva información} El mecanismo exacto por el cual la neurogénesis afecta la flexibilidad cognitiva no está del todo claro. Sin embargo, se ha propuesto que las nuevas neuronas en el \ac{gd} pueden contribuir a la flexibilidad cognitiva al permitir el olvido de memorias viejas [@akers2014] y facilitar la formación de nuevas conexiones [@toni2007], permitiendo la reconsolidación de nuevas asociaciones [@epp2016]. También se sugiere que la NHA facilita la adaptación a ambientes cambiantes al mejorar la precisión de la memoria [@lodge2019; @tuncdemir2019]. Este mecanismo está relacionado con el fenómeno de la [separación de patrones](AppendixB.qmd#term-id-7), donde las nuevas neuronas permiten la formación de engramas independientes y no superpuestos [@sahay2011]. Por último, las propiedades fisiológicas de las nuevas neuronas frente a las neuronas viejas también representan un mecanismo por el cuál la NHA afecta la [flexibilidad cognitiva](AppendixB.qmd#term-id-19): las neuronas jóvenes (4-6 semanas) tienen una mayor excitabilidad y plasticidad [@ge2007; @toni2015; @marin-burgin2012], además de mantener un tono inhibitorio en el GD gracias al reclutamiento de interneuronas [@groisman2020] e inhibición lateral de neuronas granulares maduras [@luna2019]. Esta mayor excitabilidad y plasticidad les permite competir con las neuronas viejas por la activación de engramas viejos [@anacker2017] y facilita la activación de engramas nuevos [@borzello2023].  Todos estos hallazgos sugieren que la NHA es un mecanismo ~~crucial~~ clave para la flexibilidad cognitiva y la adaptación a ambientes cambiantes, además de ser un mecanismo adaptativo que permite la actualización, un proceso crucial para el tratamiento de síntomas depresivos y de ansiedad [@maramis2021]. Sin embargo, ni la flexibilidad cognitiva [@jacobsen2023], ni la \ac{nha} [@holick2008; @bessa2009] son **necesarias** para mejorar síntomas depresivos, lo que sugiere de mecanismos adicionales involucrados en la respuesta antidepresiva.

***Otros mecanismos implicados en la flexibilidad cognitiva y la función del \ac{gd}***

*Relevancia del sistema serotoninérgico*

Diversas evidencias sugieren una relación entre cambios en la actividad y estructura de las células granulares del \ac{gd} bajo modelos de estrés y el tratamiento crónico con \ac{isrs}. @bessa2009 reportan atrofia en las dendritas del \ac{gd} y \ac{ca}3 en ratas sometidas a estrés crónico, la cual fue atenuado por el tratamiento antidepresivo, sugiriendo una recuperación de la plasticidad neuronal perdida durante el estrés. @airan2007 demostraron mediante imágenes con colorante sensible al voltaje una alteración de la actividad del \ac{gd} en un modelo de depresión por estrés crónico en ratas, mientras que el tratamiento crónico con fluoxetina prevenía este fenómeno. A nivel de receptores, la eliminación de los receptores serotoninérgicos `5-HT1A` en las células granulares resultó en la pérdida de la respuesta conductual al tratamiento con \ac{isrs} de forma crónica [@samuels2015], mientras que la restauración de estos receptores en ratones deficientes fue suficiente para mimetizar el efecto antidepresivo tras el tratamiento crónico con \ac{isrs}, proponiendo un papel terapéutico potencial para estos receptores en específico.  

Hay que destacar que utilizando técnicas de inmunohistoquímica y electrofisiología en roedores [@kobayashi2011] y primates (*Callithrix jacchus*) [@ohira2019], se han descrito otros procesos de plasticidad hipocampal inducidos por antidepresivos que podrían jugar un papel sobre la flexibilidad cognitiva. Estos grupos han descrito que la fluoxetina puede revertir neuronas granulares maduras del hipocampo a un fenotipo inmaduro, un fenómeno denominado "*demaduración*". En este fenómeno, las neuronas maduras expresan marcadores relacionados a inmaduridad ([calretinina](AppendixB.qmd#term-id-99)), reducen la expresión de marcadores de neuronas maduras ([calbindina](AppendixB.qmd#term-id-100)) y presentan propiedades electrofisiológicas características de una neurona inmadura, como aumento de excitabilidad. Al mismo tiempo, este fármaco parece reducir el número de neuronas con redes perineuronales (regiones de la matriz extracelular que regulan el desarrollo y la plasticidad de la conectividad de las neuronas) en el \ac{gd}, un fenómeno que promueve la plasticidad en el cerebro adulto. En conjunto, estos resultados podrían significar que existen otros mecanismos adicionales a la \ac{nha} que reinstauren un estado de inmadurez al \ac{gd} que representa un sustrato importante en la cognición y regulación del comportamiento [@umemori2018].

*LTP y LTD*

La \ac{ltp} y la \ac{ltd} en la formación hipocampal son mecanismos fundamentales para la codificación y almacenamiento de información espacial [@ge2010]. La \ac{ltp} en las conexiones entre las proyecciones perforantes y el \ac{gd}, así como entre las fibras musgosas y el área de \ac{ca}3, es crucial para la representación alocéntrica del entorno. \todo{dejar más claro esta parte:} Esto establece una base para los "*esquemas*", que son estructuras mentales utilizadas para codificar experiencias. Por otro lado, la \ac{ltd} en las colaterales de de Schaffer \ac{ca}3-\ac{ca}1 proporciona la base para esquemas que se reutilizan en la codificación de eventos que son similares o han sido actualizados [@dong2013]. Estos esquemas se consolidan en la neocorteza, mientras que la actualización de un esquema para integrar nueva información requiere la participación del hipocampo y de regiones corticales como la corteza retrosplenial [@hagena2024].

Por otro lado, la \ac{ltd} permite el debilitamiento de sinapsis que codifican información irrelevante, lo que facilita la actualización y flexibilidad de las memorias espaciales [@hagena2024]. Además, la \ac{ltd} desempeña un papel crucial en la modificación de los esquemas almacenados en la neocorteza [@bliss2011; @mills2014; @stacho2022]. En este contexto, la \ac{ltp} y la \ac{ltd} colaboran para formar y ajustar los *mapas cognitivos*, que son representaciones internas del entorno utilizadas para la navegación y la toma de decisiones espaciales. \todo{describir más la relación de la LTD con la flexibilidad cognitiva} El estudio de @dong2013 demostró que bloquear la LTD en el hipocampo mediante la aplicación sistémica del antagonista selectivo de \ac{glun2b}, Ro25-6981, afecta negativamente el proceso de aprendizaje reverso en el \ac{mwm}. Este hallazgo sugiere que la \ac{ltd} es esencial para la flexibilidad cognitiva necesaria para ajustar las estrategias de navegación cuando las condiciones del entorno cambian. Facilitar la \ac{ltd}, por lo tanto, puede mejorar la capacidad de los individuos para adaptar sus mapas cognitivos a nueva información, permitiendo un aprendizaje más efectivo y una adaptación a situaciones cambiantes.


*Otras estructuras implicadas en la flexibilidad cognitiva*

La posición del \ac{gd} en la red hipocampal es más compleja de lo que sugiere el flujo trisináptico canónico [@bienkowski2018]. Existen conexiones entre la \ac{ce} y \ac{ca}3 que omiten el \ac{gd}, conexiones recurrentes de \ac{ca}3 al \ac{gd} y vías adicionales entre el hipocampo y la corteza cerebral. Estas redes complican la evaluación de cómo las nuevas neuronas afectan la función hipocampal en general. Además, las neuronas recién nacidas en el \ac{gd} también proyectan a \ac{ca}2 [@llorens-martin2015], área asociada a la memoria social [@hitti2014]. Por otra parte, el **hipocampo ventral** de los roedores (hipocampo **anterior** en humanos) está implicado con los desórdenes afectivos [@seib2021] debido a su conectividad con estructuras clave en la regulación emocional, como la [amígdala](AppendixB.qmd#term-id-13) [@kim2005; @tafet2016] y los núcleos endocrinos y autonómicos del hipotálamo [@li2023; @umschweif2021]. 

Otra área sensible y crucial en la respuesta al estrés crónico es la corteza prefrontal [@arnsten2009; @cerqueira2007]. La corteza \ac{mpfc} ([mPFC](AppendixB.qmd#term-id-30)) es una región de la corteza prefrontal que proyecta al hipocampo y juega un papel crucial en la [flexibilidad cognitiva](AppendixB.qmd#term-id-19) al ajustar el comportamiento en respuesta a cambios y resolución de conflictos [@clarke2004; @ragozzino2007]. Por ejemplo, las alteraciones en la mPFC como consecuencia del estrés crónico [@belleau2019; @treadway2015] se relacionan con conductas rígidas y desarrollo de depresión y ansiedad [@mcewen2016; @jett2017]. Adicionalmente, evidencia farmacológica [@carreno2016; @fukumoto2018; @lopes-aguiar2020] sugiere que la interacción del mPFC y el hipocampo es esencial para la respuesta antidepresiva de la ketamina, un fármaco antidepresivo de rápida acción [@hales2020]. Estudiar el papel del hipocampo en la consolidación-reconsolidación de memorias, así como el papel de la mPFC para utilizar esta información [@yadav2022] y ajustar estrategias en nuevas situaciones es un punto clave para entender cómo adaptamos pensamientos y conductas en respuesta al estrés [@cerqueira2007].

## Contribuciones para el análisis en Neurociencia Cognitiva

El uso de métricas que evalúen específicamente la relevancia del hipocampo en el aprendizaje del MWM nos permitió investigar la relación entre la función hipocampal y la flexibilidad cognitiva. Específicamente, distinguir eficientemente la memoria espacial, que involucra codificar y recuperar puntos de referencia en el entorno, permitiendo a un organismo navegar y existir en el mundo. Es crucial para la supervivencia, ya que facilita la búsqueda y obtención de seguridad y alimento, y permite regresar a lugares previamente encontrados sin problemas. El presente estudio contribuye al desarrollo de modelos más efectivos en el estudio y análisis de la memoria espacial. 

***Métricas en la fase de Entrenamientos del MWM***

*Estrategias de búsqueda*

Desde 1982, @morris1982 entendía las limitaciones de utilizar las latencias de escape como una medida del aprendizaje espacial. En este artículo, Morris y colaboradores removieron por aspiración el hipocampo ventral y dorsal de ratas y observaron que estos animales, aunque aprendían la localización de la plataforma con el tiempo (menor latencia de escape), tomaban rutas menos directas hacia la plataforma en comparación de los controles. Para tratar de evaluar si el aprendizaje en los entrenamientos tenía un componente espacial, @morris1982 desarrolló un sistema de análisis de la ruta de escape que evaluava la direccionalidad de la búsqueda (ángulo hacia la plataforma). Utilizando ratones con lesiones hipocampales y corticales, este artículo identificó que el aprendizaje espacial podía ser evaluado con la direccionalidad de la trayectoria del animal: a medida que el aprendizaje espacial mejoraba, el animal tomaba una estrategia más precisa hacia la plataforma (una linea recta). Casi al mismo tiempo, @whishaw1985 desarrolló un protocolo (Corredor de Whishaw) para evaluar el tiempo y dirección de los animales para localizar la plataforma, otro enfoque para distinguir aprendizaje espacial en el MWM.

Las estrategias de búsqueda son un conjunto de comportamientos que los animales utilizan para navegar en el ambiente. El hipocampo desempeña un papel crucial en el aprendizaje espacial **alocéntrico** [@eichenbaum1999], que implica comprender las relaciones espaciales entre objetos de manera independiente del punto de vista. Las células de lugar (neuronas que se activan preferencialmente en respuesta a una localización) en el hipocampo crean mapas cognitivos (representaciones mentales estructuradas) que permiten la navegación y orientación espacial [@okeefe1990]. Además, las regiones CA3 y CA1 del hipocampo son esenciales para codificar y recuperar información espacial [@berdugo-vega2023]. Daños en el hipocampo, como en la enfermedad de Alzheimer o en el estrés crónico, afectan negativamente la capacidad de aprender y recordar mapas espaciales [@robins2022]. A pesar de la importancia de evaluar las estrategias de búsqueda para evaluar la función del hipocampo [@vouros2018] históricamente ha sido difícil evaluar esta métrica. 

Adicionalmente, la NHA afecta el aprendizaje espacial ligado a las representaciones **[alocéntricas](AppendixB.qmd#term-id-97)** [@grech2018], por lo que debe ser un punto importante para medir en el MWM si se pretende enter el efecto de la NHA sobre la cognición [@kempermann2022]. @garthe2009 suprimieron la neurogénesis adulta con \ac{tmz} (TMZ) en ratones y evaluaron su rendimiento en una tarea del \ac{mwm}, observando un déficit de aprendizaje altamente específico: los ratones tratados con este fármaco mostraron limitaciones en adoptar estrategias de búsqueda espacialmente precisas (alocéntricas), destacando el papel crucial de las nuevas neuronas en la flexibilidad y precisión del aprendizaje espacial. 

Estos hallazgos subrayan la importancia del hipocampo en la generación de mapas métricos del entorno y vinculan directamente la plasticidad celular del hipocampo con la funcionalidad cognitiva. Sin embargo, el análisis de la métrica de estrategias de búsqueda suele ser cualitativo [@othman2022]. Por otro lado, la regresión de [Poisson](AppendixB.qmd#term-id-77) utilizada para modelar las estrategias utilizadas en los entrenamientos (@fig-estrategiasPre, @fig-estrategiasPost) es una propuesta que a nuestro conocimiento no se ha utilizado en ningún otro estudio. Otros estudios [@garthe2016; @amelchenko2023a] han utilizado una regresión logística que permite comparar la probabilidad de utilizar estrategias alocéntricas *versus* estrategias [egocéntricas](AppendixB.qmd#term-id-98). Sin embargo, este enfoque no permite modelar la tercera variable de perseverancia, un tipo específico de estrategia alocéntrica que refleja una falta de flexibilidad conductual. 

Al utilizar este modelado novedoso en nuestro trabajo, comprobamos que los ratones pasan de utilizar estrategias egocéntricas a estrategias alocéntricas en los entrenamientos iniciales del MWM (@fig-estrategiasPre). Esto sugiere que el aprendizaje en esta etapa es dependiente del hipocampo [@grech2018] ya que esta estructura es fundamental para la formación de estas estrategias espaciales [@morris1982; @schwabe2007; @yu2019a]. Este enfoque mejora la comprensión de cómo los animales utilizan estrategias espaciales para resolver tareas y puede ayudar a elucidar los procesos neuronales implicados en la memoria espacial, la navegación y la flexibilidad de la conducta.

***Métricas en las Pruebas del MWM***

Las pruebas del MWM son una forma de evaluar distintos aspectos de la memoria espacial de los animales (p. ej. evocación, reconsolidación). En estas pruebas, las métricas más utilizadas son: porcentaje de tiempo en cuadrante blanco (4 cuadrantes), porcentaje de tiempo en zona blanco (definida como un círculo alrededor de la localización de la plataforma) y número de cruces (cruces alrededor de la localización de la plataforma) [@othman2022]. Sin embargo, los parámetros que reflejan con mayor precisión el desempeño en estas pruebas son: distancia promedio al *annulus* blanco y entropía [@maei2009].

*Distancia media al annulus blanco*

Esta medida calcula la distancia entre la posición del animal nadando y la ubicación de la plataforma varias veces por segundo. Como menciona @maei2009a, la distancia media al blanco es una medida más sensible que otras tradicionales (distancia de nado, velocidad, tiempo en cuadrantes y número de cruces al blanco) ya que refleja la precisión de la búsqueda de la plataforma. Los programas de seguimiento de animales actuales permiten calcular esta métrica de manera automática y precisa [@zorin2020], además que existen programas gratuitos que también facilitan el análisis de esta métrica, como *Pathfinder* con Python [@cooke2020] y Rtrack con R [@overall2020].

*Entropía*

Adicionalmente, utilizamos otra métrica más sensible al rendimiento de las pruebas del \ac{mwm} que las métricas tradicionales: *entropía* [@maei2009]. Hace casi 100 años, @tolman1927 reportaron que evaluar el número de errores durante una prueba es el mejor indicador de la capacidad de aprendizaje en laberintos, siendo más confiable que parámetros como el tiempo en resolver una tarea. Esta métrica se deriva dec los trabajos de  @shannon1948 en la teoría de información y se puede define como la incertidumbre con la que se conoce una variable. Esta incertidumbre reduce con información (aprendizaje). En el caso del \ac{mwm} [@maei2009], una incertidumbre de 0 significaría que el ratón pasó todo el tiempo en la localización de la plataforma blanco [@overall2020]; es decir, no hay error en el conocimiento de la plataforma. 

Al analizar las pruebas con esta métrica, se detectó que los ratones tratados con \textcolor{blue}{fluoxetina} mostraron una mayor entropía en la prueba de retención (@fig-entropiatodos), lo que indica que estos animales exploraron más el laberinto acuático en comparación con los ratones tratados con salina. Esto es un fenómeno similar al observado con las otras métricas, como distancia media (@fig-distanciaMedia) y tiempo en zona (@fig-zonainteraccion), donde los ratones con fluoxetina muestran menor preferencia por la zona blanco. Sin embargo, en la prueba reversa, la entropía fue similar entre todos los grupos experimentales, a diferencia de las otras métricas que encontraron diferencias entre los grupos. Como señala @meenakshi2022, esta métrica evalúa más el grado de dispersión en la prueba, más que el grado de localización (como el caso de la distancia media) en la prueba. Es decir, este parámetro estima el grado de "organización" en el rendimiento del MWM y no específicamente una propiedad espacial o de navegación. Debido a que muy pocos artículos exploran esta métrica (y hasta nuestro conocimiento ninguno en el contexto de aprendizaje reversa posterior a un protocolo de \ac{cums}), es difícil comparar e interpretar nuestros resultados. Especula. Sin embargo, la entropía podría ser un indicador de la flexibilidad cognitiva de los animales, ya que un aumento en la entropía podría reflejar una mayor exploración y búsqueda de nuevas estrategias para encontrar la plataforma en un entorno cambiante [@smaldino2015].

@smaldino2015 señala que la interpretación de la entropía en pruebas de aprendizaje se complica cuando se introduce más de una opción (más de un blanco en nuestro caso). En estos casos, un aumento de entropía podría significar cambios en los patrones de conducta que lleven al animal a tomar nuevas estrategias una vez que se identificó que la plataforma no está presente, más que una falta de aprendizaje. Por ejemplo, encontrar eficientemente un auto en un estacionamiento requiere una estrategia que permita distinguir múltiples objetivos y navegar por distintas rutas cada día, no el conocimiento y memoria perfecta de la localización del auto cada día [@garthe2013]. Es decir, el caós (entropía) en la conducta de un animal puede ser una señal de que está explorando nuevas estrategias para encontrar la plataforma, lo que podría ser un indicador de flexibilidad cognitiva. 

Al respecto, @yu2019 observaron que en ratas con \ac{nha} intacta, cuando la plataforma no estaba presente, los animales procedían a buscar una nueva ubicación. En contraste, las ratas con deficiencia en la \ac{nha} mostraban indecisión y menor exploración en esta situación de incertidumbre. El hecho de que las ratas con \ac{nha} intacta pudieran buscar una nueva ubicación posible sugiere que estas ratas tenían una mayor flexibilidad cognitiva y capacidad de adaptación a un entorno cambiante. Se ha estudiado la entropía en humanos, encontrando que niveles más altos de esta están asociados con un afecto más positivo y una mejor conectividad entre el hipocampo y el estriado [@heller2020]. Este hallazgo resalta cómo características específicas de la navegación y movimiento en el espacio, evaluadas por la entropía, están correlacionadas con estados emocionales y redes neuronales subyacentes. Estos hallazgos sugieren que la [flexibilidad cognitiva](AppendixB.qmd#term-id-19) y la capacidad de adaptación a un entorno cambiante involucran procesos cognitivos complejos que pueden aumentar la entropía a medida que surgen nuevos y complejos aprendizajes y conductas [@smaldino2015]. 

Debido a que el código original de @maei2009 utilizado para el cálculo de entropía en el MWM no está disponible ([repositorio original](http://individual.utoronto.ca/kpetrov/Matlab-codes.zip)) desde hace varios años ([Internet Archive](https://web.archive.org/web/20220808114843/http://individual.utoronto.ca/kpetrov/Matlab-codes.zip)), se derivó la formula a partir de la descripción de @maei2009 y @dajun2003 (Ver derivación a detalle en la [aplicación desarrollada](https://santi-rios.github.io/maestria_app_water_maze/)). Además, desarrollamos una aplicación web que permite a los investigadores calcular la entropía del MWM de manera sencilla y eficiente, sin la necesidad de conocimientos en programación. La aplicación se desarrolló utilizando una técnica novedosa que no necesita un servidor físico con [shinylive](https://posit-dev.github.io/r-shinylive/) y [WebAssembly](https://github.com/coatless-tutorials/convert-shiny-app-r-shinylive), por lo que no necesita costos adicionales de servidores y aseguramos que su disponibilidad en la web en el tiempo. La desventaja es que es una tecnología en desarrollo y la aplicación es lenta a comparación de correr el código en una consola de R. Finalmente, comprobamos que los resultados obtenidos con nuestro código son equivalentes a los reportados por el código original @maei2009 (@fig-entropialineplotcomps, @fig-entropialatman), lo que sugiere que nuestro código es válido y confiable para el cálculo de entropía en el MWM.

En resumen, el presente estudio resalta la necesidad de revisar y potencialmente expandir las métricas utilizadas en la investigación del MWM para capturar más fielmente los procesos cognitivos subyacentes. Al adoptar un enfoque más detallado y categorizando los comportamientos en tipos más específicos, las investigaciones pueden obtener una comprensión más profunda de las estrategias utilizadas por los animales para navegar el laberinto y resolver la tarea, lo cual puede ayudar a iluminar los mecanismos neuronales y cognitivos involucrados en el aprendizaje espacial y la memoria. Al integrar metodologías estadísticas avanzadas con rigurosos protocolos experimentales, esta investigación contribuye al perfeccionamiento de los modelos de neurociencia cognitiva y apoya el desarrollo de estrategias terapéuticas dirigidas para las deficiencias cognitivas relacionadas con el estrés.

## Perspectivas y limitaciones \todo[color=Grey!40]{Como en sus comentarios tenían dudas de ciertos resultados, o me pedían que explicara más, aquí sintetizo las limitaciones del estudio si les parece mejor.} 

<!-- >reflexiona sobre las limitaciones de tu diseño experimental, como el tamaño de la muestra, la duración del tratamiento, o posibles sesgos.
>Propón cómo futuras investigaciones podrían abordar estas limitaciones para validar o refinar tus conclusiones. -->

El presente estudio tiene varias limitaciones que deben considerarse al interpretar los resultados. En primer lugar, se observó que el grupo de salina sin protocolo de estrés-\ac{cums} mostró deficiencias en el reaprendizaje, similares a las del grupo salina-\ac{cums} (@fig-cuadrantesPRevPlot, @fig-zonaPRevPlot, @fig-latenciaspost). Este efecto podría deberse a la utilización de una cruza de ratones altamente susceptible al estrés, similar a la cepa BALB/c, como se ha reportado anteriormente [@corder2023; @palumbo2009]. Incluso inyecciones de salina pueden inducir un fenotipo ansioso en estos animales, aumentando la reactividad a corticosterona y reduciendo la diferenciación neuronal en el \ac{gd} [@dupreez2020; @drude2011; @zamora-gonzalez2013]. El poco uso de esta cepa en estudios de estrés crónico [@nollet2021] es justificando si consideramos que la descendencia de esta cepa produce fenotipos variados en el hipocampo [@crusio1990].

Por otro lado, aunque otros estudios han demostrado que la fluoxetina administrada por vía intraperitoneal durante períodos prolongados no induce conductas depresivas o ansiosas en ratones BALB/c [@norcross2008], el uso exclusivo de una cruza susceptible limita la generalización de los hallazgos. Futuros estudios deberían incorporar cepas menos vulnerables al estrés, como c57BL/6 [@corder2023; @drude2011], para descartar que los efectos observados sean consecuencia de la respuesta al estrés inducida por las inyecciones. En estudios donde se buscan correlaciones entre conductas depresivas y ansiosas y la función hipocampal suele verse afectada por diseños experimentales que no controlan estas covariables de manera adecuada [@lazic2010].

Adicionalmente, sería beneficioso incluir experimentos que permitan separar claramente los efectos antidepresivos/ansiolíticos del tratamiento (fluoxetina versus salina) de los efectos del protocolo de \ac{cums}. Esto facilitaría una estimación más precisa de las variables de respuesta y evitaría la introducción de interpretaciones erróneas derivadas de variables de control espurias [@wysocki2022]. Para abordar estos aspectos metodológicos, se contempló evaluar conductas depresivas y ansiosas (laberinto en cruz, campo abierto, nado forzado y preferencia a sacarosa); sin embargo, los resultados obtenidos (@sec-adicionales) \todo[color=green!40]{Anexo 3 no 11.} no se alinearon con lo reportado en la literatura, posiblemente debido a que la cruza empleada no es adecuada para estas pruebas.

Otro aspecto relevante que no se tomó en consideración o que podría ser revisado en un futuro es la duración del tratamiento. La mayoría de los estudios clínicos y preclínicos en \ac{isrs} se enfoca en efectos a corto o mediano plazo [@ioannidis2008], mientras que el uso de antidepresivos como la fluoxetina suele ser prolongado (meses a años) [@block2007]. Evaluar los efectos a largo plazo, así como en animales adolescentes—población en la que los antidepresivos de tipo \ac{isrs} muestran menor eficacia y mayor incidencia de efectos secundarios [@cheung2021; @zhou2020; @kryst2022; @oh2009; @boaden2020; @cipriani2016]—podría aportar una visión más completa de los mecanismos subyacentes en estos fármacos serotoninérgicos.

A pesar de que se contaban con los cerebros de los animales obtenidos en la perfusión, no se realizaron análisis histológicos para evaluar mecanismos fisiológicas regulados en nuestros grupos experimentales, como la \ac{nha} [@santarelli2003]. Aunque se ha demostrado que la fluoxetina aumenta la \ac{nha} en modelos murinos [@musaelyan2023], no se evaluó si este efecto estaba relacionado con la flexibilidad cognitiva observada en los ratones tratados con este fármaco en nuestro experimento. La evaluación de la \ac{nha} por medio de la co-localización de \ac{brdu} con marcadores como DCX (doblecortina) para identificar neuroblastos inmaduros [@olpe2023], y con NeuN y calretinina/calbindina para identificar neuronas inmaduras/maduras [@kempermann2018], respectivamente, podría proporcionar información valiosa sobre los mecanismos subyacentes a la plasticidad neuronal y su relación con la flexibilidad cognitiva. \todo[color=green!40]{Mencionas que los animales se perfundieron, sin embargo ya no utilizaste los cerebros, creo que deberías poner un párrafo en limitaciones referente a que en este trabajo no mediste la neurogenesis, pero que la literatura señala que la fluoxetina la favorece.}

La hipótesis serotoninérgica, aunque históricamente dominante en la neurobiología de la depresión [@mongeau1997], ha sido cuestionada [@harmer2017] en revisiones recientes (ver la primera revisión sistemática de esta hipótesis en @moncrieff2022). Sin embargo, desde hace tiempo [@harmer2008; @cowen2008; @lacasse2005] se ha propuesto que los antidepresivos no funcionan "restableciendo un déficit químico" de serotonina, sino que facilitan diversos procesos de plasticidad neuronal que son moldeados por el ambiente [@branchi2022; @branchi2011]. Estos procesos no están restringidos ni limitados al sistema serotoninérgico ni a la dinámica de la \ac{nha} [@holick2008; @bessa2009].

Por ejemplo, la fluoxetina, además de modular el sistema serotoninérgico, afecta otros sistemas como el glutamatérgico [@lazarevic2019; @frizzo2017]. Por ello, futuros estudios deberían explorar la interacción entre estos sistemas y evaluar fármacos moduladores del glutamato, como la ketamina [@simmler2022; @sala2022; @rawat2022; @marchi2022; @wilkowska2021; @antidepressant_berman_2000], para comprender mejor los mecanismos que median la relación entre flexibilidad cognitiva y las enfermedades mentales.

Asimismo, agentes psicoplastogénicos (fármacos que producen efectos duraderos de plasticidad neuronal estructural y/o funcional [@olson2018]) como la psilocibina, encontrada en alrededor de 200 especies de hongos [@vancourt2022], han emergido como alternativas prometedoras para tratamiento de patologías mentales donde la flexibilidad cognitiva está afectada, como adicciones [@hornick2023], trastorno por estrés postraumático [@mitchell2023], y trastornos de ansiedad y depresión [@neill2021; @higgins2021; @neill2021]. En este contexto, resulta relevante explorar la eficacia comparativa de estos agentes psicoplastogénicos frente a tratamientos antidepresivos tradicionales.

Recientemente se comparó la eficacia de la psilocibina contra el escitalopram (\ac{isrs}) [@carhart-harris2021] y se demotró que el psicoplastógeno era igual o más efectivo que el antidepresivo clásico [@nayak2023]. Estos hallazgos sugieren que la combinación o comparación de fármacos que modulen distintos sistemas –glutamatérgico y serotoninérgico– y faciliten procesos de plasticidad neuronal podría abrir nuevas estrategias terapéuticas para tratar trastornos que afectan, entre otros, la capacidad de adaptación cognitiva.

Por último, aunque hemos propuesto la \ac{nha} como un posible mecanismo que module la adaptación al cambio observada en nuestro estudio, es importante mencionar el estado actual de este campo de las neurociencias. Si bien, este proceso está bien documentada en roedores [@altman1965], la existencia y el papel funcional de la neurogénesis en humanos continúan siendo objeto de debate [@moreno-jimenez2021; @terreros-roncal2022; @sorrells2018; @sorrells2021; @paredes2018]. Aunque algunos estudios sugieren que este proceso es activo en la especie humana [@spalding2013], su relevancia en la modulación de la plasticidad cerebral y en la adaptación a cambios ambientales aún no está bien estudiada en primates [@ohira2019]. 

Como menciona @terreros-roncal2022 y @larosa2018, la presencia de \ac{nha} en humanos no implica que este proceso sea funcional o relevante para la cognición como lo es en otras especies \todo[color=Grey!40]{Esto fue un poco la conclusión de una plática que tuve con 2 expertas del tema de neurogénesis, Henriette van Praag y Angélica zepeda, en el congreso de neurobiología hace unos meses. Me pareció importante para reflejar el estado actual del campo y no caer en dogmatismos de "no existe la neurogenesis" o de "si existe y punto" y conservar el escepticismo de la ciencia}. Por ello, futuros estudios deberían explorar la relación entre la \ac{nha} y la flexibilidad cognitiva en modelos animales más cercanos a los humanos, como primates, superando las limitaciones de los modelos roedores y extrapolaciones sin fundamento a la especie humana [@bonfanti2016]. Como ejemplo de esto, @ohira2019 encontraron que la fluoxetinan en primates parece actuar más a nivel de la demaduración de neuronas en el \ac{gd} que en la \ac{nha}, lo que sugiere que la plasticidad neuronal en el hipocampo adulto puede ser más compleja de lo que se ha propuesto en modelos roedores [@umemori2018].

Superar estas limitaciones en investigaciones futuras permitirá obtener una visión más integral y precisa de cómo interactúan la neurogénesis, la plasticidad sináptica y los tratamientos antidepresivos en la regulación de la flexibilidad cognitiva para el tratamiento de trastornos mentales.